#!/usr/bin/perl /usr/bin/BridgeDealer
<--
  doc/examples/shapeclass

  Part of:
  BridgeDealer - hand dealing system
  Copyright (c) 2000 Michal J. Kubski
  All rights reserved.

  Generates deals where South has 'freakish' hand
  and North has 'balanced'.

  'freakish' and 'balanced' are shape classes
  defined in 'lib/shapes.dh'.
 
-->
<dealer>
    <lib>
        BridgeDealer.dh
    </lib>
    <include>
        lib/shapes.dh
    </include>
    <code>
        my $d = new BridgeDealer;
        for (my $i=0; $i<10; $i++) { 
            print $i+1,".\n\n";            
            do {
                $d->deal();
            } until freakish($d,$SOUTH) && balanced($d,$NORTH);
            $d->tableprint();
        }
    </code>
</dealer>